services:
  car2-server:
    type: node
    env:
      NODE_ENV: production
      PORT: 8080
      CHROME_BIN: /usr/bin/chromium-browser
      ID_NUMBER: A102574899
      PASSWORD: visi319VISI
    build:
      command: npm install
    deploy:
      command: npm start

  car2-client:
    type: web
    source: ./client
    env:
      REACT_APP_API_URL: https://car2-server.zeabur.app
    build:
      command: |
        cd client
        npm install
        npm run build
    deploy:
      command: npx serve -s build -l 8080 