services:
  car2-server:
    type: node
    source: ./server
    env:
      NODE_ENV: production
      PORT: 3001
      CHROME_BIN: /usr/bin/chromium-browser
      ID_NUMBER: A102574899
      CAR_PASSWORD: visi319VISI
    build:
      command: npm install
    deploy:
      startCommand: node index.js

  car2-client:
    type: static
    source: ./client/build
    env:
      REACT_APP_API_URL: ${ZEABUR_SERVICE_URL_car2-server}
    build:
      command: cd ../client && npm install && npm run build 